# Generated by Django 4.0.5 on 2022-06-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalAssetManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
